server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercesystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  security:
    user:
      roles: admin
      name: xykkk
      password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 3000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: xykkk
    password: 123456
    publisher-returns: on
    virtual-host: /ecommerce


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800  #604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
  doctorAuthority: doctor:write_and_read
  managerAuthority: manager:write_and_read