server:
  port: 8091
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    max-http-form-post-size: 0

spring:
  datasource:
    url: jdbc:mysql://47.105.66.104:3306/ecommercesystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  security:
    user:
      roles: admin
      name: xykkk
      password: 123456
  rabbitmq:
    host: 47.105.66.104
    port: 5672
    username: admin
    password: 123456
    publisher-returns: on
    virtual-host: /ecommerce
  http:
    multipart:
      max-file-size: 32MB #注意单位
      max-request-size: 32MB #注意单位

  mail:
    host: smtp.qq.com
    username: 1005131042@qq.com
    password: fwgbgkuvmmzrbfgi
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory: javax.net.ssl.SSLSoccketFactory
          ssl:
            enable: true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800  #604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
  doctorAuthority: doctor:write_and_read
  managerAuthority: manager:write_and_read
